# -*- coding: utf-8 -*-
"""test_PyData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jcr7mxZ1Lsde7OZa4BQ1URUvpGNNjdtE
"""

def hello():
  print("Hello World")

def PyData():
  print("yay")


